### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by SharhadBashar** [zengxianyu/jsws#17]
I was running your code, and after 30,000 iterations, I got this error:

`Traceback (most recent call last):
  File "/home/s2bashar/anaconda3/envs/thesis/lib/python3.6/multiprocessing/queues.py", line 234, in _feed
  File "/home/s2bashar/anaconda3/envs/thesis/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
  File "/home/s2bashar/anaconda3/envs/thesis/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 333, in reduce_storage
RuntimeError: unable to open shared memory object </torch_20991_592962625> in read-write mode
`

**Comment by SharhadBashar** [comment]
another follow up error after iter 31500:
`train: 182it [00:22,  8.21it/s]
Traceback (most recent call last):
  File "weak_seg_full_sal_train.py", line 504, in <module>
  File "weak_seg_full_sal_train.py", line 459, in train
  File "weak_seg_full_sal_train.py", line 149, in val_voc
  File "/home/s2bashar/Desktop/Thesis/jsws/evaluate_seg.py", line 119, in evaluate_iou
  File "/home/s2bashar/anaconda3/envs/thesis/lib/python3.6/multiprocessing/context.py", line 119, in Pool
  File "/home/s2bashar/anaconda3/envs/thesis/lib/python3.6/multiprocessing/pool.py", line 156, in __init__
  File "/home/s2bashar/anaconda3/envs/thesis/lib/python3.6/multiprocessing/pool.py", line 250, in _setup_queues
  File "/home/s2bashar/anaconda3/envs/thesis/lib/python3.6/multiprocessing/context.py", line 112, in SimpleQueue
  File "/home/s2bashar/anaconda3/envs/thesis/lib/python3.6/multiprocessing/queues.py", line 315, in __init__
  File "/home/s2bashar/anaconda3/envs/thesis/lib/python3.6/multiprocessing/context.py", line 67, in Lock
  File "/home/s2bashar/anaconda3/envs/thesis/lib/python3.6/multiprocessing/synchronize.py", line 162, in __init__
  File "/home/s2bashar/anaconda3/envs/thesis/lib/python3.6/multiprocessing/synchronize.py", line 59, in __init__
OSError: [Errno 24] Too many open files
`

**Comment by zengxianyu** [comment]
you'll need to change the allowed opened files of your system to avoid this error
